<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
</head>
<body>
    <h1>Login Form</h1>
    <form action="{{url("users")}}" method="post" enctype="multipart/form-data">
        <label>username</label>
        <input type="text" name="username">
        <br><br>
        <label>password</label>
        <input type="password" name="password">
        <br><br>
        <input type="submit" name="submit">
    </form>
</body>
</html>