<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href=<?php echo BASE_URL ?>>Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href=<?php echo BASE_URL.'/book' ?>>Book</a>
    </li>
  </ul>
</nav>

<?php echo PHP_EOL ?>
<?php echo PHP_EOL ?>
<?php echo PHP_EOL ?>

<?php foreach ($books as $book) { ?>
<div class="card" style="box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);transition: 0.3s;width: 40%;">
  <div class="container" style="padding: 2px 16px;">
    <a href="<?php echo BASE_URL ?>/Book/show/<?php echo $book->id ?>"><h4><b><?php echo $book->title; ?></b></h4></a>
    <p><?php echo "by: ".$book->book_author->name; ?></p>
    <p><?php echo $book->summary; ?></p>
    <p><?php echo $book->release_date; ?></p>
    <a href="<?php echo BASE_URL ?>/Book/delete/<?php echo $book->id ?>"><b><?php echo 'Delete'; ?></b></a>
    <a href="<?php echo BASE_URL ?>/Book/edit/<?php echo $book->id ?>"><b><?php echo 'Edit'; ?></b></a>
  </div>
</div>
<?php } ?>